//User API----------------------------------------------------------------------------------
### Create user

POST http://localhost:8000/add-user
Content-Type: application/json

{   
    "email" : "hendra@gmail.com",
    "firstName" : "Hendra",
    "lastName" : "Wijaya",
    "address" : "Sydney",
    "mobileNumber" : "12345678"
}

###create user

POST https://dev-uconnex.azurewebsites.net/get-user
Content-Type: application/json

{   
    "email" : "hendra3@gmail.com"

}